[build]
  base = ""                # leave blank if root folder
  command = "npm run build"
  publish = ".next"        # or "out" if using `next export`

[[plugins]]
  package = "@netlify/plugin-nextjs"
